# 差分ビルド設定
[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"

# セキュリティ対策
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

# キャッシュ関連
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=60480000"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=60480000, immutable"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=60480000, immutable"
